name: update-data
on: [push]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Goto in the scripts folder
        run: cd scripts

      - name: Run update.py
        run: python update.py
